---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: echo
  namespace: flux-system
spec:
  filterTags:
    extract: $version
    pattern: ^(?P<version>v\d+\.\d+\.\d+(-\d+)?).*-slim
  imageRepositoryRef:
    name: echo
  policy:
    alphabetical:
      order: asc
